### ISSUE TITLE
Override or transform label values

### ISSUE THREAD

**Issue by madprogramer** [mayer79/shapviz#7]
The default behaviour of [sv_waterfall](https://github.com/mayer79/shapviz#waterfall-plot) and [sv_forceplot](https://github.com/mayer79/shapviz#force-plot) is to print out the associated value for a given attribute:
 ![image](https://user-images.githubusercontent.com/3719664/175503212-651caa91-628d-413e-a7ec-73ffd7c37913.png)

This is good, but a bit confusing when working with pre-processed data (f.x. normalised values). It would be very nice if the labels could be overridden or "transformed" in the final plot.

**Comment by mayer79** [comment]
In this case I suggest to simply use the unnormalized data as `X` when creating the `shapviz` object. It is only used for visualization.  If you pass me an example, I can show you what I mean.

**Comment by madprogramer** [comment]
Yeah, I know there are ways to do it (like tidyverse workflows letting you retain the original values for later).

But still, what if someone wants to apply a new transformation, f.x. limiting the digit precision to 2 on numeric labels?

**Comment by mayer79** [comment]
There is an argument `format_fun`: Function used to format numeric feature values and SHAP values. Currently, this function is used to format both feature values and SHAP values. So there is *some*, but not full flexibility here. Do you think we need more flexibility here?

**Comment by mayer79** [comment]
As a first step, the formatter of SHAP values will be separated from the formatter of feature values. More flexibility might be added later, e.g., passing a list of formatters for the features.

**Comment by mayer79** [comment]
1. There is no good reason to represent a binary variable by two columns in a tree-based model. So let's consider a situation with an unordered categorical with > 2 levels.
2. I think new versions of XGBoost got some initial support of categoricals, so there is no need to create dummies anymore and the problem is solved. 
3. Often, ordinal encoding works sufficiently well, even if the categorical is unordered (and has only few levels). This will solve the problem as well.
4. If you insist on situations with an 1:m mapping between an "explanation" column in X and the corresponding SHAP columns, then you can always use the ingenious property that SHAP values are additive and manually calculate the row sums of the columns as an intermediate step. If you post an artificial example, I can show what I mean.

**Comment by mayer79** [comment]
At least partly implemented in https://github.com/mayer79/shapviz/pull/12

**Comment by mayer79** [comment]
Here the new "collapse" logic: it will deal with one-hot encoded columns in the prediction data:

``` r
devtools::install_github("mayer79/shapviz")
library(shapviz)

X_pred <- stats::model.matrix(~ . -1, iris[, -1])
head(X_pred)
dtrain <- xgboost::xgb.DMatrix(X_pred, label = as.integer(iris[, 1]))
fit <- xgboost::xgb.train(data = dtrain, nrounds = 50)
x <- shapviz(
  fit,
  X_pred = X_pred,
  X = iris[, -1],
  collapse = list(Species = c("Speciessetosa", "Speciesversicolor", "Speciesvirginica"))
)
sv_waterfall(x)
```
